language: python
python:
  - "3.5"
# command to install dependencies
install:
  - sudo apt-get update
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Install needed packages
  - conda install flake8
  # Useful for debugging any issues with conda
  - conda info -a

  # Replace dep1 dep2 ... with your dependencies
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION numpy scipy pandas matplotlib
  - source activate test-environment

# command to run tests
script:
  - flake8 --max-line-length=120

notifications:
  email: false
  slack:
    machlearn:4bsIJqghcxMDEgyfxzi0EIa1
    on_failure: always
    on_success: change
